# **Instruções**

A técnica de vectorização em Numpy que vimos na última aula é muito útil para quando necessitamos de transformar os dados de uma estrutura (ex.: vector, matriz, etc...).

Deve criar um notebook Jupyter, procurando escrever o código necessário para resolver os problemas seguintes, explicando por palavras suas o que fez. As justificações escritas, bem como a boa apresentação do notebook serão levados em conta.

1. Crie uma matriz e um vector com dimensões à sua escolha, com valores inteiros aleatórios entre 0 e 20, ambos incluídos.
Usando uma das duas técnicas de vectorização apresentadas na aula anterior, construa uma estrutura equivalente em dimensões à da matriz e do vector iniciais, em que os respetivos valores sejam de acordo com o seguinte:
- entre 0 e 6 --> "FRACO"
- entre 7 e 9 --> "INSUFICIENTE"
- entre 10 e 13 --> "SUFICIENTE"
- entre 14 e 16 --> "BOM"
- entre 17 e 18 --> "MUITO BOM"
- entre 19 e 20 --> "EXCELENTE"


2. Crie uma matriz de dimensões 4x5 com valores inteiros aleatórios entre 0 e 100.  

a) Usando uma das técnicas de vectorização, transforme os valores da matriz de modo a que cada valor seja convertido na proporção do mesmo relativamente à soma dos valores em linha

b) Aplique a mesma técnica, mas relativamente à soma dos valores em coluna

In [1]:
import numpy as np
import pandas as pd

## 1.

In [2]:
matriz = np.random.randint(0, 21, size=(4,5))
matriz

array([[18,  6,  1,  3, 11],
       [12, 20, 13, 16,  2],
       [ 2,  4,  4, 11, 11],
       [14,  0,  7, 10, 20]])

In [3]:
vetor = np.random.randint(0, 21, size=5)
vetor

array([ 7, 12,  4, 18, 13])

In [4]:
def aplicar_notas(valor):
    if 0 <= valor <= 6:
        return "FRACO"
    elif 7 <= valor <= 9:
        return "INSUFICIENTE"
    elif 10 <= valor <= 13:
        return "SUFICIENTE"
    elif 14 <= valor <= 16:
        return "BOM"
    elif 17 <= valor <= 18:
        return "MUITO BOM"
    elif 19 <= valor <= 20:
        return "EXCELENTE"
    
teste_vec = np.vectorize(aplicar_notas)
print(teste_vec(vetor))
print(teste_vec(matriz))

['INSUFICIENTE' 'SUFICIENTE' 'FRACO' 'MUITO BOM' 'SUFICIENTE']
[['MUITO BOM' 'FRACO' 'FRACO' 'FRACO' 'SUFICIENTE']
 ['SUFICIENTE' 'EXCELENTE' 'SUFICIENTE' 'BOM' 'FRACO']
 ['FRACO' 'FRACO' 'FRACO' 'SUFICIENTE' 'SUFICIENTE']
 ['BOM' 'FRACO' 'INSUFICIENTE' 'SUFICIENTE' 'EXCELENTE']]


No exercício 1., optei por utilizar a função .randit() do módulo .random da biblioteca numpy para construir uma matriz e um vetor com valores aleatórios entre 0 e 20 (valores inclusivos). A matriz possui 5 colunas e 4 linhas.  
Depois, defini uma função de nome 'aplicar_notas(valor)', em que o parametro 'valor' irá retornar uma determinada classificação (em string), consoante o intervalo definido em cada uma das condições e mediante o valor gerado pela função .randit() na construção das estruturas de dados acima referidas.  


A seguir, criei uma variável 'test_vec' que irá conter a função vectorize() da biblioteca numpy aplicado à função 'aplicar_notas'.   
A função .vectorize() é útil porque permite converte uma função 'Python padrão (standard)' numa função vetorizada. A vetorização, no contexto do NumPy, refere-se à capacidade de aplicar uma função a todos os elementos de uma matriz ou vetor de uma só vez, sem a necessidade de usar 'loops'. Ao usar np.vectorize,é possível  transformar uma função que normalmente opera em valores únicos, numa função que opera em 'arrays' NumPy, aplicando a função a cada elemento do 'array'.  

## 2.

In [5]:
matriz_2 = np.random.randint(0, 101, size=(4,5))
matriz_2

array([[27, 27, 43, 38, 95],
       [81, 85, 85, 47, 82],
       [ 8, 80, 81, 68, 37],
       [84, 68, 48, 82, 68]])

#### a)

In [6]:
somas_linha = matriz_2.sum(axis=1, keepdims=True)
print(somas_linha)
matriz_proporcional_linha = matriz_2 / somas_linha
print(matriz_proporcional_linha)

[[230]
 [380]
 [274]
 [350]]
[[0.1173913  0.1173913  0.18695652 0.16521739 0.41304348]
 [0.21315789 0.22368421 0.22368421 0.12368421 0.21578947]
 [0.02919708 0.2919708  0.29562044 0.24817518 0.1350365 ]
 [0.24       0.19428571 0.13714286 0.23428571 0.19428571]]


#### b)

In [7]:
somas_coluna = matriz_2.sum(axis=0, keepdims=True)
print(somas_coluna)
matriz_proporcional_coluna = matriz_2 / somas_coluna
print(matriz_proporcional_coluna)

[[200 260 257 235 282]]
[[0.135      0.10384615 0.16731518 0.16170213 0.33687943]
 [0.405      0.32692308 0.3307393  0.2        0.29078014]
 [0.04       0.30769231 0.3151751  0.2893617  0.13120567]
 [0.42       0.26153846 0.18677043 0.34893617 0.24113475]]


No exercício 2, utilizei a função '.randint()' do módulo '.random' da biblioteca 'NumPy' para criar uma matriz com valores inteiros aleatórios no intervalo de 0 a 100, incluindo ambos os extremos. A matriz resultante possui 5 colunas e 4 linhas.

Em seguida, apliquei a função '.sum()' do 'NumPy' para calcular a soma dos valores por linha (usando o parâmetro axis=1) e por coluna (com o parâmetro axis=0). Defini o parâmetro 'keepdims' como 'True', o que permite preservar as dimensões da matriz, mantendo os resultados das somas ao longo do eixo especificado na função.

Posteriormente, para normalizar a matriz_2 em relação "à proporção dos valores da mesma relativamente à soma dos valores em cada linha e coluna", criei a variável 'matriz_proporcional'. Esta variável contém o resultado da divisão dos valores originais da matriz_2 pelas somas previamente calculadas das linhas e colunas, respectivamente.

#### 2. a), b) - alternativo

In [8]:
def soma(v):
    return v/v.sum()



In [9]:
np.apply_along_axis(soma, 1, matriz_2)

array([[0.1173913 , 0.1173913 , 0.18695652, 0.16521739, 0.41304348],
       [0.21315789, 0.22368421, 0.22368421, 0.12368421, 0.21578947],
       [0.02919708, 0.2919708 , 0.29562044, 0.24817518, 0.1350365 ],
       [0.24      , 0.19428571, 0.13714286, 0.23428571, 0.19428571]])

In [10]:
np.apply_along_axis(soma, 0, matriz_2)

array([[0.135     , 0.10384615, 0.16731518, 0.16170213, 0.33687943],
       [0.405     , 0.32692308, 0.3307393 , 0.2       , 0.29078014],
       [0.04      , 0.30769231, 0.3151751 , 0.2893617 , 0.13120567],
       [0.42      , 0.26153846, 0.18677043, 0.34893617, 0.24113475]])

Outra técnica de vetorização para obter o mesmo resultado é através da função apply_along_axis() da biblioteca NumPy, que permite aplicar uma função definida ao longo de um eixo específico (especificado como segundo parâmetro da função apply_along_axis()) de um array multidimensional. 

Neste caso, a função definida por mim consiste em retornar o valor obtido pela divisão entre os diversos valores da matriz_2 (criada inicialmente) e os valores obtidos nas somas dos valores de cada uma das linhas/colunas.  


## Conclusão

A vetorização permite aplicar funções de forma eficiente a todos os elementos de uma estrutura de dados como por exemplo uma matriz ou vetor, sem recorrer a necessidade de aplicar 'loops'. A vetorização simplifica o código, tornando-o mais legível. 